### PR TITLE
don't update rustup

### LINKED ISSUE #108: rustup randomly dies updating itself in CI? (windows-only?)
When trying to build releases for my rust cli tool https://github.com/fritzrehde/watchbind, I get:
```
info: downloading self-update
error: could not copy file from 'C:\Users\runneradmin\.cargo\bin\rustup-init.exe' to 'C:\Users\runneradmin\.cargo\bin\rustup.exe': Access is denied. (os error 5)
ResourceUnavailable: D:\a\_temp\7f52b54c-ff40-4eed-a91a-8b2bb5e42c67.ps1:2
Line |
   2 |  rustup update stable && rustup default stable
     |                          ~~~~~~~~~~~~~~~~~~~~~
     | Program 'rustup.exe' failed to run: An error occurred trying to start process
     | 'C:\Users\runneradmin\.cargo\bin\rustup.exe' with working directory 'D:\a\watchbind\watchbind'. Access is
     | denied.At D:\a\_temp\7f52b54c-ff40-4eed-a91a-8b2bb5e42c67.ps1:2 char:25 + rustup update stable && rustup default
     | stable +                         ~~~~~~~~~~~~~~~~~~~~~.
```
for the windows build.

### PR DESCRIPTION
**Pull request by Gankra**
ostensibly fixes #108

### CODE REVIEW

File: cargo-dist/src/ci.rs [hunk 1]
```diff
@@ -58,9 +58,13 @@ fn write_github_ci<W: std::io::Write>(f: &mut W, dist: &DistGraph) -> Result<(),
     }
 
     // Install Rust with rustup
-    // FIXME: we get some warnings from Github about hardcoded rust tools being on PATH
+    //
+    // We pass --no-self-update to work around https://github.com/rust-lang/rustup/issues/2441
```
Comment (ashleygwilliams) [inline cargo-dist/src/ci.rs:62]: oh my. we should note this for when we want to implement self-update ourselves

**Review by ashleygwilliams — APPROVED** [review]
