### PR TITLE
fix: windows use powershell to extract zip file

### LINKED ISSUE #2004: Npm install does not work on windows
## Description

The npm install script depends on commands like "unzip" which as far as I can see are not provided with windows by default (At least they're not apart of my install)

Image

This results in the following error when trying to install the package on windows:

`npm error Error fetching release: spawnSync unzip ENOENT`

### PR DESCRIPTION
**Pull request by jacobtread**
## Description

For windows platforms the unzip utility is not on systems by default, this changes it so that on windows powershell is used in combination with Expand-Archive to extract the zip file.

## Changes
- Extend "Package" to take in the platform
- Add case in zip extraction for the windows platform to use powershell Expand-Archive instead of unzip

## Related Issues
- Closes #2004

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thank you very much! I appreciate this! I'll give it a test and see how it works.

It looks like `prettier` is flagging a couple of requested formatting changes. Are you up for tweaking that? I can take care of it if you prefer.

The snapshots we use for tests will need to be updated with these changes. I can do that for you if you'd like, or you can do it by following these steps:

* Install [cargo insta](https://insta.rs/docs/cli/)
* Run the tests with `cargo test`
* Run `cargo insta accept`
* Commit and push the changes

**Comment by jacobtread** [comment]
Hi, I have updated the formatting :) I will need you to please handle the test snapshots updating I think If I run them on my device it will cause lots of problems, as running the tests on my machine ends up failing a majority of unrelated integration and snapshot tests (I'd assume because I'm using windows and the tests don't take that into account) thank you!

Edit: The errors I was getting might've just been me running from the top level project, running the tests and cargo insta accept from the cargo-dist sub directory got me more acceptable outputs, I've commited the new snapshots for this

**Comment by mistydemeo** [comment]
Thanks! Looks like one snapshot didn't take, so I've pushed a commit with that.

**Comment by mistydemeo** [comment]
Looking good! I'll just do some testing on my Windows machine later to make sure all works as I expect, but I think this should be good.

**Comment by jacobtread** [comment]
Awesome thank you :)

**Comment by jacobtread** [comment]
Is there anything I can do to push this one forward for a new release? I'm hoping to use this in one of my projects some time soon  :) 

If not thats okay I can look into manually having it go up to npm separately 

Edit: found the cargo-dist-url-override option :) so I'm all good no need to rush with this

**Comment by mistydemeo** [comment]
Sorry for the delay! I’ve just been very busy lately, and hope to have time to integrate and release this soon.

File: cargo-dist/templates/installer/npm/binary-install.js [hunk 1]
```diff
@@ -122,12 +124,25 @@ class Package {
...
-                ]);
+                let result;
+                if (this.platform.includes("windows")) {
+                  // Windows does not have "unzip" by default on many installations, instead
+                  // we use Expand-Archive from powershell
+                  result = spawnSync("powershell.exe", [
+                    "-NoProfile",
+                    "-NonInteractive",
+                    "-Command",
+                    `Expand-Archive -LiteralPath '${tempFile}' -DestinationPath '${this.installDirectory}' -Force`,
```
Comment (mistydemeo) [inline cargo-dist/templates/installer/npm/binary-install.js:135]: Just had a realization. Does this introduce the possibility of shell injection? Previously that wasn't possible because `spawnSync` is being run with `shell=false`, but in this version the unzip command is being passed to powershell as a single command string. Could mean that install directories or tempfile names with powershell parameters in them could do things here they don't in the other paths.

Comment (jacobtread) [reply cargo-dist/templates/installer/npm/binary-install.js:135]: Yes I think you are right there, I will have a look into other possible ways of executing the command

**Comment by jacobtread** [comment]
> Sorry for the delay! I’ve just been very busy lately, and hope to have time to integrate and release this soon.

It's no worries!

I have modified the command to use args to prevent shell injection in the install dir / temp file name. 

I've updated the snapshots that would run for me the "axolotlsay_basic" test is failing on my machine due to "failed to generate an OmniBOR Artifact ID (status: exit code: 2)" so If you could please run that on your machine for me if I've missed any snapshots 😄

File: cargo-dist/templates/installer/npm/binary-install.js [hunk 2]
```diff
@@ -122,12 +124,27 @@ class Package {
...
-                ]);
+                let result;
+                if (this.platform.includes("windows")) {
+                  // Windows does not have "unzip" by default on many installations, instead
+                  // we use Expand-Archive from powershell
+                  result = spawnSync("powershell.exe", [
+                    "-NoProfile",
+                    "-NonInteractive",
+                    "-Command",
+                    "& { Expand-Archive -LiteralPath $args[0] -DestinationPath $args[1] -Force }",
```
Comment (StartAutomating) [inline cargo-dist/templates/installer/npm/binary-install.js:135]: Expand-Archive is safe, but this technique of embedding isn't always so secure.

Essentially, because you're passing down an unquoted string in thru, it could theoretically get expanded into something nasty.  In practice, you'll probably be fine if the inputs are sanitized first (say, by confirming the file exists).

I'd personally feel more comfortable if the command were something like:

~~~PowerShell
& {param([string]$LiteralPath, [string]$DestinationPath) Expand-Archive @psboundParameters } 
~~~

This would force each parameter to be a single string, and pass the parameters directly down to Expand-Path.

Comment (mistydemeo) [reply cargo-dist/templates/installer/npm/binary-install.js]: Great, thank you!

**Comment by jacobtread** [comment]
Thank you!

**Comment by mistydemeo** [comment]
I'll try to get a new release out soon.

**Comment by jacobtread** [comment]
> I'll try to get a new release out soon.

No rush from me :) I'm using a fork I published for the time being thank you for merging though!

**Comment by jacobtread** [comment]
@mistydemeo Hold off on deploying this to a release, I miss understood the .platform didn't realize that was an object, missed the line that pulled the object for it in from the package.json so the .includes is failing for zip installs I'll open a PR shortly
