### PR TITLE
fix: Add `.tar.zst` suffix for Zstd

### LINKED ISSUE #1064: Filename extension for Zstd should be `.zst`
According to [RFC 8478](https://datatracker.ietf.org/doc/html/rfc8478#autoid-51), the filename extension for Zstd should be `.zst` instead of `.zstd`.

### PR DESCRIPTION
**Pull request by sorairolake**
Closes #1064

### CODE REVIEW

File: cargo-dist/src/config.rs [hunk 1]
```diff
@@ -980,9 +980,9 @@ impl<'de> Deserialize<'de> for ZipStyle {
             ".zip" => Ok(ZipStyle::Zip),
             ".tar.gz" => Ok(ZipStyle::Tar(CompressionImpl::Gzip)),
             ".tar.xz" => Ok(ZipStyle::Tar(CompressionImpl::Xzip)),
-            ".tar.zstd" => Ok(ZipStyle::Tar(CompressionImpl::Zstd)),
```
Comment (ashleygwilliams) [inline cargo-dist/src/config.rs:983]: for backwards compatibility, we'll probably want to keep this around for at least a few releases. would you mind updating to accept both `zstd` and `zst`?

**Review by ashleygwilliams — APPROVED** [review]
