### PR TITLE
fix(ci): always serialize upload_files

### LINKED ISSUE #1387: cargo-dist autoselects non-GitHub remote and fails
The problem I'm experiencing is this:
```
  × GitHub CI support requires a GitHub repository
  ╰─▶   × Your repository URL https://<not github> couldn't be parsed.
        help: Only GitHub URLs are supported at the moment.
```

The repo in question has two remotes: one `origin` that points at something that's not GitHub and one `github` that *does* point at GitHub.

Is there a way for me to tell cargo-dist to just use the GH remote?

### PR DESCRIPTION
**Pull request by mistydemeo**
While it's usually an error if we received a totally empty set of artifacts, it's possible in the global build job under a very specific set of conditions:

* There are no installers, *and*
* The source tarball was disabled

In this case we need to make sure we still provide an upload_files array in the manifest so that we can always index into it.

Fixes #1387.

### CODE REVIEW

File: cargo-dist-schema/src/lib.rs [hunk 1]
```diff
@@ -106,7 +106,6 @@ pub struct DistManifest {
     pub linkage: Vec<Linkage>,
     /// Files to upload
```
Comment (ashleygwilliams) [inline cargo-dist-schema/src/lib.rs:107]: do you think we may want to leave a comment here about why we want to serialize the empty array?

Comment (mistydemeo) [reply cargo-dist-schema/src/lib.rs:107]: Good callout, done.

**Review by Gankra — APPROVED** [review]
